# Numpy Arrays

In [7]:
# multidimensional array library

import numpy as np

In [ ]:
li1 = [1,2,3]
li2 = [4,5,6]

# this gives error!
x = li1*li2
print(x)

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([3,4,5])

# this works! 
y = arr1 * arr2
print(y)

[ 3  8 15]


In [17]:
# 2d arrays:

d2d = np.array([[1,2,3],[5,5,5]])
print(d2d)

[[1 2 3]
 [5 5 5]]


In [ ]:
# Get the dimension
# o número de eixos (ou dimensões) de um vetor é dado pelo atributo 'ndim', enquanto o número total de elementos é dado por 'size'

d2d.ndim

2

In [ ]:
# Get the shape
# esse atributo indica a forma do vetor (no caso, o vetor é: 2,3 Ou seja: tem duas linhas e 3 colunas)

d2d.shape

(2, 3)

In [ ]:
# Get Type
# o tipo dos elementos de um ndarray pode ser acessado por meio do atributo dtype
d2d.dtype

dtype('int64')

In [ ]:
# specifing the type:
# o tipo desejado pode ser espeficicado na criação do array

d3d = np.array([[1,2,3],[5,5,5]], dtype='int16')
d3d.dtype

dtype('int16')

In [ ]:
# Get the number of elements:

d2d.size

6

# Accessing/Changing specific elements, rows, columns, etc

In [25]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# Get a specific element(s) [row, column]
print(a[1,4])
print(a[0,2])
print(a[0][1:4])
print(a[1, :])

10
3
[2 3 4]
[ 6  7  8  9 10]


In [39]:
# Get elements (s) [row, column]

print(a[:, 2])

[3 8]


In [40]:
a[1,4] = 50
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 50]]


In [44]:
# 3d array:

arr3d = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(arr3d.shape)
print(arr3d.ndim)
print(arr3d.dtype)
print(arr3d)

(2, 2, 2)
3
int64
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [46]:
# Get specific element (work outside in)

print(arr3d[0,1,1])

4


In [47]:
arr3d[0,1,1] = 30
print(arr3d)

[[[ 1  2]
  [ 3 30]]

 [[ 5  6]
  [ 7  8]]]
