In [1]:
import numpy as np

# Initializing different types of arrays

## All 0s matrix

In [2]:
# All 0s matrix

a = np.zeros((2,3)) # specifing the shape
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
b = np.zeros((2,3,3,2))
print(b)

[[[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]]


In [4]:
b.ndim

4

## All 1s matrix

In [5]:
c = np.ones((2,4))
print(c)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Any other number

In [6]:
d = np.full((2,2,3), 99)
print(d)

[[[99 99 99]
  [99 99 99]]

 [[99 99 99]
  [99 99 99]]]


In [7]:
# Any other number (full_like)

e = np.full_like(a, 4)
print(e)

[[4. 4. 4.]
 [4. 4. 4.]]


# função diag

In [9]:
f = np.diag([10,10,10,10])
print(f)

[[10  0  0  0]
 [ 0 10  0  0]
 [ 0  0 10  0]
 [ 0  0  0 10]]


# função arange

In [10]:
g = np.arange(0,5)
print(g)

[0 1 2 3 4]


In [11]:
h = np.arange(0,6,2)
print(h)

[0 2 4]


# função linspace

In [12]:
i = np.linspace(0,5,10)
print(i)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
