In [1]:
import numpy as np

# Initializing different types of arrays

## All 0s matrix

In [7]:
# All 0s matrix

a = np.zeros((2,3)) # specifing the shape
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
b = np.zeros((2,3,3,2))
print(b)

[[[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]]


In [9]:
b.ndim

4

## All 1s matrix

In [11]:
c = np.ones((2,4))
print(c)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Any other number

In [13]:
d = np.full((2,2,3), 99)
print(d)

[[[99 99 99]
  [99 99 99]]

 [[99 99 99]
  [99 99 99]]]


In [14]:
# Any other number (full_like)

e = np.full_like(a, 4)
print(e)

[[4. 4. 4.]
 [4. 4. 4.]]
