In [1]:
import numpy as np

# Random numbers

In [3]:
# random decimal numbers
a = np.random.rand(5,2,4)
print(a)

[[[0.91059129 0.67081922 0.69876869 0.96051062]
  [0.80291226 0.65087697 0.37747599 0.90466255]]

 [[0.78121731 0.82805935 0.57135911 0.43602288]
  [0.29873948 0.45776011 0.15795723 0.01790874]]

 [[0.21617684 0.28235069 0.67257592 0.11252989]
  [0.19924195 0.04612443 0.96067298 0.4962165 ]]

 [[0.25674781 0.96345149 0.80000535 0.92883469]
  [0.68651021 0.70744705 0.23498234 0.50737386]]

 [[0.68450663 0.19948903 0.968767   0.50261822]
  [0.83616613 0.42846528 0.22127184 0.26902133]]]


In [5]:
# Random integer numbers

b = np.random.randint(7, size=(3,3))
print(b)

[[2 1 4]
 [5 4 0]
 [3 5 6]]


# Identity matrix

In [6]:
c = np.identity(5)
print(c)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [10]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 4, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [13]:
output = np.ones((5,5))
#print(output)

z = np.zeros((3,3))
z[1,1] = 9

output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
