In [1]:
import numpy as np

# Basic mathematics with numpy

In [2]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])

In [3]:
a += 2
print(a)

[3 4 5 6]


In [5]:
ab = a / 2
print(ab)

[1.5 2.  2.5 3. ]


In [6]:
c = a + b
print(c)

[13 24 35 46]


In [7]:
cc= c**2
print(cc)

[ 169  576 1225 2116]


In [8]:
# Take the sin
sin = np.sin(c)
print(sin)

[ 0.42016704 -0.90557836 -0.42818267  0.90178835]


In [9]:
cos = np.cos(cc)
print(cos)

[ 0.79849619 -0.46377546  0.97564915  0.13691638]
