In [1]:
import numpy as np

# Linear algebra

In [3]:
a = np.ones((2,3))
b = np.full((3,2), 2)

print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


## matrix multiplication

In [4]:
c = np.matmul(a,b)
print(c)

[[6. 6.]
 [6. 6.]]
