In [1]:
import numpy as np

# Basic statistics

In [2]:
stats = np.array([[1,2,3], [4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [3]:
mean = np.mean(stats)
maxi = np.max(stats)
mini = np.min(stats)
suma = np.sum(stats)

print(mean)
print(maxi)
print(mini)
print(suma)

3.5
6
1
21


In [ ]:
# Mean of the first column

mean_col_1 = np.mean(stats[:, 0])
print(mean_col_1)

2.5


In [5]:
# correlation of first and second colum:

corr = np.corrcoef(stats[:, 0], stats[:, 1])
print(corr)

[[1. 1.]
 [1. 1.]]
