In [1]:
import numpy as np

# Reorganizing arrays

### Reshape

In [2]:
before = np.array([[1,2,3,4], [5,6,7,8]])

before.shape

(2, 4)

In [3]:
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


### Vertically stacking vectors

In [4]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

v3 = np.vstack([v1, v2])
print(v3)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
v4 = np.vstack([v3, v2, v1])
print(v4)

[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [1 2 3 4]]


### horizontal stack

In [6]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

h3 = np.hstack((h1, h2))

print(h3)

[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]
